[packages.abxbus]
repository = "ArchiveBox/abxbus"
tag_prefix = ""
downstream_repository = "ArchiveBox/abxpkg"
downstream_branch = "main"
update_mode = "lock"
version_scheme = "patch"

[packages.abxpkg]
repository = "ArchiveBox/abxpkg"
tag_prefix = "v"
downstream_repository = "ArchiveBox/abx-plugins"
downstream_branch = "main"
update_mode = "exact"
version_scheme = "patch"

[packages.abx-plugins]
repository = "ArchiveBox/abx-plugins"
tag_prefix = "v"
downstream_repository = "ArchiveBox/abx-dl"
downstream_branch = "main"
update_mode = "exact"
version_scheme = "patch"

[packages.abx-dl]
repository = "ArchiveBox/abx-dl"
tag_prefix = "v"
downstream_repository = "ArchiveBox/ArchiveBox"
downstream_branch = "dev"
update_mode = "exact"
version_scheme = "rc"

[packages.archivebox]
repository = "ArchiveBox/ArchiveBox"
tag_prefix = "v"
downstream_repository = ""
downstream_branch = ""
update_mode = ""
version_scheme = ""
